version: '3.0'

services:
  grafana:
    container_name: 'qxip-flow'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-10.0.1}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/qxip-flow
      - ./provisioning:/etc/grafana/provisioning
